modLoader="kotlinforforge"
loaderVersion="[4,)"
license='LGPL'

[[mods]]
modId="kotlinforforge"
version="@VERSION@"
displayName="Kotlin For Forge Continuation"
logoFile="kotlinforforge_icon.png"
credits="thedarkcolour and his \"minions\""
authors="thedarkcolour"
description='''
Makes Kotlin forge-friendly
'''
[[dependencies.kotlinforforge]]
modId="minecraft"
mandatory=true
type="required"
versionRange="[1.19.3,1.21)"
ordering="NONE"
side="BOTH"
[modproperties.kotlinforforge]
catalogueImageIcon="kotlinforforge_icon.png"
